---
name: instagramroutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'auth//instagram/': 'Iliain\Instagram\Controllers\InstagramAuthController'
    'auth//facebook/': 'Iliain\Instagram\Controllers\InstagramAuthController'
